CREATE DATABASE financeiro;

\c financeiro;

CREATE TABLE "Users" (
  "id" VARCHAR PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "name" VARCHAR NOT NULL,
  "email" VARCHAR NOT NULL UNIQUE,
  "password" VARCHAR NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Transactions" (
  "id" VARCHAR PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  "type" VARCHAR NOT NULL,
  "amount" NUMERIC NOT NULL,
  "description" VARCHAR NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "userId" VARCHAR NOT NULL REFERENCES "Users"("id") ON DELETE CASCADE
);
